version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: "daily"
    time: "03:00"
    timezone: "UTC"
  open-pull-requests-limit: 10

- package-ecosystem: docker
  directory: "/.devcontainer/"
  schedule:
    interval: "daily"
    time: "03:00"
    timezone: "UTC"
  open-pull-requests-limit: 10

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "weekly"
    day: "wednesday"
    time: "03:00"
    timezone: "UTC"
  open-pull-requests-limit: 20
  target-branch: main

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "thursday"
    time: "03:00"
    timezone: "UTC"
  open-pull-requests-limit: 10
  target-branch: main
